### ISSUE TITLE
Links in Wiki is broken

### ISSUE THREAD

**Issue by GanZ2016** [radu-pisoi/com.oxygenxml.pdf2.ug#4]
The link of "4.First page in a chapter" in the Wiki page is broken, please fix it.

Thanks!

**Comment by raducoravu** [comment]
I just did that, thanks for noticing, the target of the link is here: https://github.com/oxygenxml/com.oxygenxml.pdf2.ug/wiki/Customizing-the-First-Page-of-a-Chapter
